//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class c_cp
    {
        public int id_cp { get; set; }
        public string cp { get; set; }
        public string nb_tipo_asentamiento { get; set; }
        public string nb_asentamiento { get; set; }
        public string nb_municipio { get; set; }
        public string nb_ciudad { get; set; }
        public string nb_estado { get; set; }
        public string nb_zona { get; set; }
        public string cl_tipo_asentamiento { get; set; }
        public string cl_municipio { get; set; }
        public string cl_ciudad { get; set; }
        public string cl_estado { get; set; }
    }
}
