//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class c_establecimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public c_establecimiento()
        {
            this.h_acceso_establecimiento = new HashSet<h_acceso_establecimiento>();
            this.k_cnts_01_002 = new HashSet<k_cnts_01_002>();
            this.k_cnts_01_003_a = new HashSet<k_cnts_01_003_a>();
            this.k_cnts_01_003_b = new HashSet<k_cnts_01_003_b>();
            this.k_cnts_01_003_c = new HashSet<k_cnts_01_003_c>();
            this.c_informe = new HashSet<c_informe>();
        }
    
        public int id_establecimiento { get; set; }
        public string uuid { get; set; }
        public Nullable<int> folio_secuencial { get; set; }
        public string codigo_establecimiento { get; set; }
        public System.DateTime fe_registro { get; set; }
        public string folio_licencia_sanitaria { get; set; }
        public Nullable<System.DateTime> fe_emision_licencia_sanitaria { get; set; }
        public Nullable<System.DateTime> fe_vigencia_licencia_sanitaria { get; set; }
        public string folio_aviso_responsable { get; set; }
        public Nullable<System.DateTime> fe_emision_aviso_responsable { get; set; }
        public Nullable<System.DateTime> fe_vigencia_aviso_responsable { get; set; }
        public string nb_establecimiento { get; set; }
        public string razon_social { get; set; }
        public string rfc { get; set; }
        public string calle { get; set; }
        public string no_ext { get; set; }
        public string no_int { get; set; }
        public string entre_calle1 { get; set; }
        public string entre_calle2 { get; set; }
        public string cp { get; set; }
        public string colonia { get; set; }
        public string municipio { get; set; }
        public string ciudad { get; set; }
        public int id_entidad_federativa { get; set; }
        public string nb_responsable { get; set; }
        public string ap_responsable { get; set; }
        public string am_responsable { get; set; }
        public string especialidad_responsable { get; set; }
        public string cedula_responsable { get; set; }
        public string email_principal_responsable { get; set; }
        public string email_alterno_responsable { get; set; }
        public string telefono_fijo_responsable { get; set; }
        public string telefono_ext_responsable { get; set; }
        public string telefono_movil_responsable { get; set; }
        public string nb_director_unidad { get; set; }
        public string ap_director_unidad { get; set; }
        public string am_director_unidad { get; set; }
        public string especialidad_director_unidad { get; set; }
        public string cedula_director_unidad { get; set; }
        public string email_principal_director_unidad { get; set; }
        public string email_alterno_director_unidad { get; set; }
        public string telefono_fijo_director_unidad { get; set; }
        public string telefono_ext_director_unidad { get; set; }
        public string telefono_movil_director_unidad { get; set; }
        public string observaciones { get; set; }
        public string password { get; set; }
        public string password_anterior { get; set; }
        public string nb_archivo_1 { get; set; }
        public string nb_archivo_2 { get; set; }
        public bool pregunta_1 { get; set; }
        public bool pregunta_2 { get; set; }
        public bool esta_activo { get; set; }
        public Nullable<System.DateTime> fe_ultimo_acceso { get; set; }
        public Nullable<System.DateTime> fe_cambio_password { get; set; }
        public int id_tipo_establecimiento { get; set; }
        public int id_institucion { get; set; }
        public int id_estatus_establecimiento { get; set; }
    
        public virtual c_entidad_federativa c_entidad_federativa { get; set; }
        public virtual c_estatus_establecimiento c_estatus_establecimiento { get; set; }
        public virtual c_institucion c_institucion { get; set; }
        public virtual c_tipo_establecimiento c_tipo_establecimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<h_acceso_establecimiento> h_acceso_establecimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<k_cnts_01_002> k_cnts_01_002 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<k_cnts_01_003_a> k_cnts_01_003_a { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<k_cnts_01_003_b> k_cnts_01_003_b { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<k_cnts_01_003_c> k_cnts_01_003_c { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<c_informe> c_informe { get; set; }
    }
}
