//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class c_periodo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public c_periodo()
        {
            this.k_cnts_01_002 = new HashSet<k_cnts_01_002>();
            this.k_cnts_01_003_a = new HashSet<k_cnts_01_003_a>();
            this.k_cnts_01_003_b = new HashSet<k_cnts_01_003_b>();
            this.k_cnts_01_003_c = new HashSet<k_cnts_01_003_c>();
        }
    
        public int id_periodo { get; set; }
        public string cl_periodo { get; set; }
        public string nb_periodo { get; set; }
        public System.DateTime fe_apertura { get; set; }
        public Nullable<System.DateTime> fe_cierre { get; set; }
        public bool esta_activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<k_cnts_01_002> k_cnts_01_002 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<k_cnts_01_003_a> k_cnts_01_003_a { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<k_cnts_01_003_b> k_cnts_01_003_b { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<k_cnts_01_003_c> k_cnts_01_003_c { get; set; }
    }
}
