//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class c_usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public c_usuario()
        {
            this.h_acceso_usuario = new HashSet<h_acceso_usuario>();
            this.h_password = new HashSet<h_password>();
            this.c_rol = new HashSet<c_rol>();
        }
    
        public int id_usuario { get; set; }
        public string cl_usuario { get; set; }
        public string nb_usuario { get; set; }
        public string password { get; set; }
        public string password_anterior { get; set; }
        public string email_principal { get; set; }
        public string no_telefono { get; set; }
        public string nb_puesto { get; set; }
        public Nullable<System.DateTime> fe_ultimo_acceso { get; set; }
        public Nullable<System.DateTime> fe_cambio_password { get; set; }
        public int no_intento_acceso { get; set; }
        public Nullable<System.DateTime> fe_ultimo_intento_acceso { get; set; }
        public bool fe_nuevo_intento_acceso { get; set; }
        public bool es_super_usuario { get; set; }
        public bool esta_activo { get; set; }
        public int id_estatus_usuario { get; set; }
    
        public virtual c_estatus_usuario c_estatus_usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<h_acceso_usuario> h_acceso_usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<h_password> h_password { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<c_rol> c_rol { get; set; }
    }
}
