//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class h_excepcion
    {
        public int id_excepcion { get; set; }
        public System.DateTime fe_excepcion { get; set; }
        public string ds_excepcion { get; set; }
        public string nb_metodo { get; set; }
        public Nullable<int> id_funcion { get; set; }
    
        public virtual c_funcion c_funcion { get; set; }
    }
}
