//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class k_cnts_01_003_a
    {
        public int id_cnts_01_003_a { get; set; }
        public System.DateTime fe_registro { get; set; }
        public Nullable<System.DateTime> fe_envio { get; set; }
        public string uuid { get; set; }
        public string nb_archivo_informe { get; set; }
        public bool esta_activo { get; set; }
        public int id_establecimiento { get; set; }
        public int id_periodo { get; set; }
    
        public virtual c_establecimiento c_establecimiento { get; set; }
        public virtual c_periodo c_periodo { get; set; }
        public virtual k_secc_a_tabla_01 k_secc_a_tabla_01 { get; set; }
        public virtual k_secc_a_tabla_02 k_secc_a_tabla_02 { get; set; }
        public virtual k_secc_a_tabla_03 k_secc_a_tabla_03 { get; set; }
        public virtual k_secc_a_tabla_04 k_secc_a_tabla_04 { get; set; }
        public virtual k_secc_a_tabla_05 k_secc_a_tabla_05 { get; set; }
        public virtual k_secc_a_tabla_06 k_secc_a_tabla_06 { get; set; }
        public virtual k_secc_a_tabla_07 k_secc_a_tabla_07 { get; set; }
        public virtual k_secc_a_tabla_08 k_secc_a_tabla_08 { get; set; }
    }
}
