//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class k_secc_a_tabla_02
    {
        public int id_cnts_01_003_a { get; set; }
        public short r01_c01 { get; set; }
        public short r01_c02 { get; set; }
        public short r01_c03 { get; set; }
        public short r01_c04 { get; set; }
        public short r01_c05 { get; set; }
        public short r01_c06 { get; set; }
        public short r01_c07 { get; set; }
        public short r01_c08 { get; set; }
        public short r01_c09 { get; set; }
    
        public virtual k_cnts_01_003_a k_cnts_01_003_a { get; set; }
    }
}
