//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_establecimiento
    {
        public long ID { get; set; }
        public string codigo_establecimiento { get; set; }
        public string nb_establecimiento { get; set; }
        public string nb_tipo_establecimiento { get; set; }
        public string nb_institucion { get; set; }
        public string nb_entidad_federativa { get; set; }
        public int id_establecimiento { get; set; }
    }
}
